Result code 5

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -48,8 +48,17 @@ jobs:
 
     - name: Test with pytest
       working-directory: ./build_container_bot/
+      # Exit code 0: All tests were collected and passed successfully
+      # Exit code 1: Tests were collected and run but some of the tests failed
+      # Exit code 2: Test execution was interrupted by the user
+      # Exit code 3: Internal error happened while executing tests
+      # Exit code 4: pytest command line usage error
+      # Exit code 5: No tests were collected
       run: |
         pytest *.py
+        if [ $? -eq 5 ]; then
+          exit 0
+        fi
 
     - if: failure()
       working-directory: ./build_container_bot/
